const DEFAULT_AERON_URI = "aeron:ipc?term-length=4m"

"""
Return a default ProducerConfig for API use (no TOML).
"""
function default_producer_config(;
    aeron_dir::AbstractString = "",
    aeron_uri::AbstractString = DEFAULT_AERON_URI,
    descriptor_stream_id::Int32 = Int32(1100),
    control_stream_id::Int32 = Int32(1000),
    qos_stream_id::Int32 = Int32(1200),
    metadata_stream_id::Int32 = Int32(1300),
    stream_id::UInt32 = UInt32(10000),
    producer_id::UInt32 = UInt32(1),
    layout_version::UInt32 = UInt32(1),
    nslots::UInt32 = UInt32(1024),
    shm_base_dir::AbstractString = "/dev/shm",
    shm_namespace::AbstractString = "tensorpool",
    producer_instance_id::AbstractString = "",
    header_uri::AbstractString = "",
    payload_pools::Vector{PayloadPoolConfig} = [PayloadPoolConfig(UInt16(1), "", UInt32(1_048_576), nslots)],
    announce_interval_ns::UInt64 = UInt64(1_000_000_000),
    qos_interval_ns::UInt64 = UInt64(1_000_000_000),
    progress_interval_ns::UInt64 = UInt64(250_000),
    progress_bytes_delta::UInt64 = UInt64(65_536),
    mlock_shm::Bool = false,
)
    instance_id = isempty(producer_instance_id) ? string(uuid4()) : String(producer_instance_id)
    return ProducerConfig(
        String(aeron_dir),
        String(aeron_uri),
        descriptor_stream_id,
        control_stream_id,
        qos_stream_id,
        metadata_stream_id,
        stream_id,
        producer_id,
        layout_version,
        nslots,
        String(shm_base_dir),
        String(shm_namespace),
        instance_id,
        String(header_uri),
        payload_pools,
        UInt8(MAX_DIMS),
        announce_interval_ns,
        qos_interval_ns,
        progress_interval_ns,
        progress_bytes_delta,
        mlock_shm,
    )
end

"""
Return a default ConsumerConfig for API use (no TOML).
"""
function default_consumer_config(;
    aeron_dir::AbstractString = "",
    aeron_uri::AbstractString = DEFAULT_AERON_URI,
    descriptor_stream_id::Int32 = Int32(1100),
    control_stream_id::Int32 = Int32(1000),
    qos_stream_id::Int32 = Int32(1200),
    stream_id::UInt32 = UInt32(10000),
    consumer_id::UInt32 = UInt32(1),
    expected_layout_version::UInt32 = UInt32(1),
    mode::Mode.SbeEnum = Mode.STREAM,
    max_outstanding_seq_gap::UInt32 = UInt32(0),
    use_shm::Bool = true,
    supports_shm::Bool = true,
    supports_progress::Bool = false,
    max_rate_hz::UInt16 = UInt16(0),
    payload_fallback_uri::AbstractString = "",
    shm_base_dir::AbstractString = "/dev/shm",
    require_hugepages::Bool = false,
    progress_interval_us::UInt32 = UInt32(250),
    progress_bytes_delta::UInt32 = UInt32(65_536),
    progress_major_delta_units::UInt32 = UInt32(0),
    hello_interval_ns::UInt64 = UInt64(1_000_000_000),
    qos_interval_ns::UInt64 = UInt64(1_000_000_000),
    announce_freshness_ns::UInt64 = UInt64(3_000_000_000),
    requested_descriptor_channel::AbstractString = "",
    requested_descriptor_stream_id::UInt32 = UInt32(0),
    requested_control_channel::AbstractString = "",
    requested_control_stream_id::UInt32 = UInt32(0),
    mlock_shm::Bool = false,
)
    allowed_base_dirs = isempty(shm_base_dir) ? String[] : [String(shm_base_dir)]
    return ConsumerConfig(
        String(aeron_dir),
        String(aeron_uri),
        descriptor_stream_id,
        control_stream_id,
        qos_stream_id,
        stream_id,
        consumer_id,
        expected_layout_version,
        UInt8(MAX_DIMS),
        mode,
        max_outstanding_seq_gap,
        use_shm,
        supports_shm,
        supports_progress,
        max_rate_hz,
        String(payload_fallback_uri),
        String(shm_base_dir),
        allowed_base_dirs,
        require_hugepages,
        progress_interval_us,
        progress_bytes_delta,
        progress_major_delta_units,
        hello_interval_ns,
        qos_interval_ns,
        announce_freshness_ns,
        String(requested_descriptor_channel),
        requested_descriptor_stream_id,
        String(requested_control_channel),
        requested_control_stream_id,
        mlock_shm,
    )
end
