module Core

using ..ShmTensorpoolControl
using ..ShmTensorpoolDriver
using ..ShmTensorpoolBridge
using ..ShmTensorpoolDiscovery
using ..ShmTensorpoolTraceLink
using ..SBE
include("telemetry.jl")
using .Telemetry
include("logging.jl")
using .TPLog
include("fixed_string.jl")
include("metadata.jl")
include("qos_api.jl")
include("messages.jl")
include("errors.jl")

export TensorPoolError,
    TelemetrySink,
    NoopTelemetrySink,
    telemetry_enabled,
    telemetry_sink,
    set_telemetry_sink!,
    update_telemetry_settings!,
    emit_log!,
    emit_counter!,
    maybe_emit_log!,
    maybe_emit_counter!,
    FixedString,
    MetadataAttribute,
    MetadataEntry,
    DEFAULT_METADATA_TEXT_FORMAT,
    DEFAULT_METADATA_BINARY_FORMAT,
    METADATA_CHUNK_MAX,
    validate_metadata_chunks,
    AbstractQosMonitor,
    QosProducerSnapshot,
    QosConsumerSnapshot,
    poll_qos!,
    producer_qos,
    consumer_qos,
    MAX_DIMS,
    RegionType,
    Dtype,
    MajorOrder,
    MessageHeader,
    FrameDescriptor,
    FrameProgress,
    ProgressUnit,
    ClockDomain,
    ConsumerConfigMsg,
    ConsumerHello,
    QosConsumer,
    Mode,
    QosProducer,
    ShmPoolAnnounce,
    ShmRegionSuperblock,
    SlotHeaderMsg,
    TensorHeaderMsg,
    DataSourceAnnounce,
    DataSourceMeta,
    encode_consumer_config!,
    encode_metadata_announce!,
    encode_metadata_meta!,
    DriverMessageHeader,
    DriverHugepagesPolicy,
    DriverResponseCode,
    DriverRole,
    DriverPublishMode,
    DriverLeaseRevokeReason,
    DriverShutdownReason,
    ShmAttachRequest,
    ShmAttachResponse,
    ShmDetachRequest,
    ShmDetachResponse,
    ShmLeaseKeepalive,
    ShmDriverShutdown,
    ShmLeaseRevoked,
    ShmDriverShutdownRequest,
    BridgeMessageHeader,
    BridgeBool,
    BridgeFrameChunk,
    DiscoveryMessageHeader,
    DiscoveryRequest,
    DiscoveryResponse,
    DiscoveryStatus,
    TraceLinkMessageHeader,
    TraceLinkSet,
    MESSAGE_HEADER_LEN,
    DRIVER_MESSAGE_HEADER_LEN,
    BRIDGE_MESSAGE_HEADER_LEN,
    DISCOVERY_MESSAGE_HEADER_LEN,
    TRACELINK_MESSAGE_HEADER_LEN,
    DISCOVERY_GROUP_HEADER_LEN,
    DISCOVERY_VAR_ASCII_HEADER_LEN,
    FRAME_DESCRIPTOR_LEN,
    FRAME_PROGRESS_LEN,
    QOS_PRODUCER_LEN,
    QOS_CONSUMER_LEN,
    CONSUMER_HELLO_LEN,
    SLOT_HEADER_BLOCK_LEN,
    TENSOR_HEADER_LEN,
    TEMPLATE_FRAME_DESCRIPTOR,
    TEMPLATE_FRAME_PROGRESS,
    TEMPLATE_SHM_POOL_ANNOUNCE,
    TEMPLATE_CONSUMER_CONFIG,
    TEMPLATE_CONSUMER_HELLO,
    TEMPLATE_QOS_CONSUMER,
    TEMPLATE_QOS_PRODUCER,
    TEMPLATE_DATA_SOURCE_ANNOUNCE,
    TEMPLATE_DATA_SOURCE_META,
    TEMPLATE_SHM_ATTACH_REQUEST,
    TEMPLATE_SHM_ATTACH_RESPONSE,
    TEMPLATE_SHM_DETACH_REQUEST,
    TEMPLATE_SHM_DETACH_RESPONSE,
    TEMPLATE_SHM_LEASE_KEEPALIVE,
    TEMPLATE_SHM_DRIVER_SHUTDOWN,
    TEMPLATE_SHM_LEASE_REVOKED,
    TEMPLATE_SHM_DRIVER_SHUTDOWN_REQUEST,
    TEMPLATE_BRIDGE_FRAME_CHUNK,
    TEMPLATE_DISCOVERY_REQUEST,
    TEMPLATE_DISCOVERY_RESPONSE,
    matches_message_schema,
    matches_message_header,
    matches_driver_schema,
    matches_driver_header,
    matches_discovery_header,
    matches_tracelink_header,
    sbe_message_length

end
