module Core

using ..ShmTensorpoolControl
using ..ShmTensorpoolDriver
using ..ShmTensorpoolBridge
using ..ShmTensorpoolDiscovery
using ..SBE
using ..Timers

include("constants.jl")
include("logging.jl")
using .TPLog
include("fixed_string.jl")
include("messages.jl")
include("types.jl")
include("errors.jl")
include("validation.jl")

export AeronInitError,
    AttachRejectedError,
    AttachTimeoutError,
    BridgeConfigError,
    DiscoveryConfigError,
    DiscoveryTimeoutError,
    ShmUriError,
    ShmValidationError,
    TensorPoolError,
    FixedString,
    PayloadPoolConfig,
    ProducerConfig,
    ConsumerSettings,
    BridgeMapping,
    BridgeStreamIdRange,
    BridgeConfig,
    PayloadView,
    SlotClaim,
    DiscoveryConfig,
    DiscoveryRegistryEndpoint,
    DiscoveryRegistryConfig,
    DiscoveryPoolEntry,
    DiscoveryEntry,
    DiscoveryResultView,
    discovery_result_view,
    payload_view,
    MAGIC_TPOLSHM1,
    SUPERBLOCK_SIZE,
    HEADER_SLOT_BYTES,
    DEFAULT_FRAGMENT_LIMIT,
    CONTROL_BUF_BYTES,
    ANNOUNCE_BUF_BYTES,
    DRIVER_URI_MAX_BYTES,
    DRIVER_ERROR_MAX_BYTES,
    DISCOVERY_SCHEMA_ID,
    DISCOVERY_MAX_RESULTS_DEFAULT,
    DISCOVERY_MAX_DATASOURCE_NAME_BYTES,
    DISCOVERY_RESPONSE_BUF_BYTES,
    DISCOVERY_INSTANCE_ID_MAX_BYTES,
    DISCOVERY_CONTROL_CHANNEL_MAX_BYTES,
    DISCOVERY_TAG_MAX_BYTES,
    DISCOVERY_MAX_TAGS_PER_ENTRY_DEFAULT,
    DISCOVERY_MAX_POOLS_PER_ENTRY_DEFAULT,
    DISCOVERY_RESULT_BLOCK_LEN,
    MAX_DIMS,
    RegionType,
    Dtype,
    MajorOrder,
    MessageHeader,
    FrameDescriptor,
    FrameProgress,
    ConsumerConfigMsg,
    ConsumerHello,
    QosConsumer,
    Mode,
    QosProducer,
    ShmPoolAnnounce,
    ShmRegionSuperblock,
    TensorSlotHeaderMsg,
    DataSourceAnnounce,
    DataSourceMeta,
    DriverMessageHeader,
    DriverHugepagesPolicy,
    DriverResponseCode,
    DriverRole,
    DriverPublishMode,
    DriverLeaseRevokeReason,
    DriverShutdownReason,
    ShmAttachRequest,
    ShmAttachResponse,
    ShmDetachRequest,
    ShmDetachResponse,
    ShmLeaseKeepalive,
    ShmDriverShutdown,
    ShmLeaseRevoked,
    ShmDriverShutdownRequest,
    BridgeMessageHeader,
    BridgeBool,
    BridgeFrameChunk,
    DiscoveryMessageHeader,
    DiscoveryRequest,
    DiscoveryResponse,
    DiscoveryStatus,
    MESSAGE_HEADER_LEN,
    DRIVER_MESSAGE_HEADER_LEN,
    BRIDGE_MESSAGE_HEADER_LEN,
    DISCOVERY_MESSAGE_HEADER_LEN,
    DISCOVERY_GROUP_HEADER_LEN,
    DISCOVERY_VAR_ASCII_HEADER_LEN,
    FRAME_DESCRIPTOR_LEN,
    FRAME_PROGRESS_LEN,
    QOS_PRODUCER_LEN,
    QOS_CONSUMER_LEN,
    CONSUMER_HELLO_LEN,
    TEMPLATE_FRAME_DESCRIPTOR,
    TEMPLATE_FRAME_PROGRESS,
    TEMPLATE_SHM_POOL_ANNOUNCE,
    TEMPLATE_CONSUMER_CONFIG,
    TEMPLATE_CONSUMER_HELLO,
    TEMPLATE_QOS_CONSUMER,
    TEMPLATE_QOS_PRODUCER,
    TEMPLATE_DATA_SOURCE_ANNOUNCE,
    TEMPLATE_DATA_SOURCE_META,
    TEMPLATE_SHM_ATTACH_REQUEST,
    TEMPLATE_SHM_ATTACH_RESPONSE,
    TEMPLATE_SHM_DETACH_REQUEST,
    TEMPLATE_SHM_DETACH_RESPONSE,
    TEMPLATE_SHM_LEASE_KEEPALIVE,
    TEMPLATE_SHM_DRIVER_SHUTDOWN,
    TEMPLATE_SHM_LEASE_REVOKED,
    TEMPLATE_SHM_DRIVER_SHUTDOWN_REQUEST,
    TEMPLATE_BRIDGE_FRAME_CHUNK,
    TEMPLATE_DISCOVERY_REQUEST,
    TEMPLATE_DISCOVERY_RESPONSE,
    sbe_message_length,
    validate_discovery_endpoints,
    validate_bridge_config

end
