module AeronTensorPool

using Aeron
using Agent
using Clocks
using FixedSizeArrays
using Hsm
using Mmap
using SBE
using StringViews
using UnsafeArrays

include("gen/ShmTensorpoolControl.jl")
using .ShmTensorpoolControl
include("gen/ShmTensorpoolDriver.jl")
using .ShmTensorpoolDriver
include("gen/ShmTensorpoolBridge.jl")
using .ShmTensorpoolBridge
include("gen/ShmTensorpoolDiscovery.jl")
using .ShmTensorpoolDiscovery

include("core/constants.jl")
include("core/logging.jl")
using .TPLog
include("core/fixed_string.jl")
include("core/messages.jl")
include("timers/polled_timer.jl")
include("core/types.jl")
include("core/errors.jl")
include("core/validation.jl")
include("shm/uri.jl")
include("shm/linux.jl")
include("shm/backend.jl")
include("shm/paths.jl")
include("shm/slots.jl")
include("shm/seqlock.jl")
include("shm/superblock.jl")
include("aeron/aeron_utils.jl")
include("aeron/counters.jl")
include("control/runtime.jl")
include("control/proxies.jl")
include("control/pollers.jl")
include("driver/driver.jl")
include("client/driver_client.jl")
include("client/discovery_client.jl")
include("client/client_api.jl")
include("agents/producer/producer.jl")
include("agents/consumer/consumer.jl")
include("agents/supervisor/supervisor.jl")
include("agents/bridge/bridge.jl")
include("agents/discovery/discovery.jl")
include("agents/producer_agent.jl")
include("agents/consumer_agent.jl")
include("agents/supervisor_agent.jl")
include("agents/driver_agent.jl")
include("agents/bridge_agent.jl")
include("agents/bridge_system_agent.jl")
include("agents/discovery_agent.jl")
include("agents/discovery_registry_agent.jl")
include("config/config_loader.jl")

export AeronInitError,
    AttachRequestProxy,
    AttachRequestHandle,
    AttachRejectedError,
    AttachTimeoutError,
    AttachResponse,
    BridgeAgent,
    BridgeSystemAgent,
    BridgeConfigError,
    BridgeAssembledFrame,
    BridgeConfig,
    BridgeCounters,
    BridgeHooks,
    BridgeMapping,
    BridgeReceiverState,
    BridgeSenderState,
    BridgeSourceInfo,
    BridgeSystemConfig,
    ConsumerAgent,
    ConsumerConfigMsg,
    ConsumerCounters,
    ConsumerFrameView,
    ConsumerHello,
    ConsumerHooks,
    ConsumerInfo,
    ConsumerSettings,
    ConsumerState,
    ConsumerHandle,
    Counters,
    DetachRequestProxy,
    DetachResponse,
    DiscoveryConfigError,
    DiscoveryTimeoutError,
    DiscoveryAgent,
    DiscoveryClientState,
    DiscoveryMessageHeader,
    DiscoveryConfig,
    DiscoveryEntry,
    DiscoveryPoolEntry,
    DiscoveryRegistryConfig,
    DiscoveryRegistryAgent,
    DiscoveryRegistryEndpoint,
    DiscoveryRequest,
    DiscoveryResponse,
    DiscoveryResultView,
    DiscoveryResponseSlot,
    DiscoveryStatus,
    DiscoveryProviderState,
    DiscoveryRegistryState,
    DriverAgent,
    DriverClientState,
    DriverConfig,
    DriverCounters,
    DriverEndpoints,
    DriverHugepagesPolicy,
    DriverLeaseRevokeReason,
    DriverMessageHeader,
    DriverPolicies,
    DriverPool,
    DriverPoolConfig,
    DriverProfileConfig,
    DriverPublishMode,
    DriverResponseCode,
    DriverResponsePoller,
    DriverRole,
    DriverShmConfig,
    DriverShutdown,
    DriverShutdownReason,
    DriverState,
    DriverStreamConfig,
    Dtype,
    FixedString,
    FrameDescriptor,
    FrameProgress,
    HEADER_SLOT_BYTES,
    KeepaliveProxy,
    LeaseRevoked,
    MAGIC_TPOLSHM1,
    MAX_DIMS,
    MajorOrder,
    MessageHeader,
    Mode,
    PayloadPoolConfig,
    PayloadView,
    PolledTimer,
    ProducerAgent,
    ProducerConfig,
    ProducerCounters,
    ProducerHooks,
    ProducerInfo,
    ProducerState,
    ProducerHandle,
    QosConsumer,
    QosProducer,
    RegionType,
    SUPERBLOCK_SIZE,
    ShmAttachRequest,
    ShmAttachResponse,
    ShmDetachRequest,
    ShmDetachResponse,
    ShmDriverShutdown,
    ShmDriverShutdownRequest,
    ShmLeaseKeepalive,
    ShmLeaseRevoked,
    ShmRegionSuperblock,
    ShmUri,
    ShmUriError,
    ShmValidationError,
    SlotClaim,
    SuperblockFields,
    SupervisorAgent,
    SupervisorConfig,
    SupervisorCounters,
    SupervisorHooks,
    SupervisorState,
    SystemConfig,
    TensorPoolClient,
    TensorPoolContext,
    TensorPoolError,
    TensorSlotHeader,
    TensorSlotHeaderMsg,
    TimerSet,
    add_counter,
    attach_consumer,
    attach_producer,
    connect,
    apply_consumer_config!,
    bridge_forward_announce!,
    bridge_receiver_do_work!,
    bridge_rematerialize!,
    bridge_send_frame!,
    bridge_sender_do_work!,
    canonical_epoch_dir,
    canonical_header_uri,
    canonical_pool_uri,
    canonical_shm_paths,
    consumer_do_work!,
    do_work,
    driver_client_do_work!,
    driver_do_work!,
    discovery_result_view,
    discovery_do_work!,
    discovery_registry_do_work!,
    discover_streams!,
    due!,
    emit_announce!,
    emit_consumer_config!,
    emit_consumer_hello!,
    emit_progress_complete!,
    emit_qos!,
    handle_consumer_hello!,
    handle_shm_pool_announce!,
    header_commit_ptr,
    header_commit_ptr_from_offset,
    header_slot_offset,
    init_bridge_receiver,
    init_bridge_sender,
    init_consumer,
    init_consumer_from_attach,
    init_discovery_provider,
    init_discovery_registry,
    init_discovery_client,
    init_driver,
    init_driver_client,
    init_producer,
    init_producer_from_attach,
    init_supervisor,
    load_bridge_config,
    load_consumer_config,
    load_driver_config,
    load_producer_config,
    load_supervisor_config,
    load_system_config,
    make_control_assembler,
    make_counter_type_id,
    make_descriptor_assembler,
    make_qos_assembler,
    map_from_announce!,
    map_from_attach_response!,
    mmap_shm,
    next_header_index,
    parse_shm_uri,
    payload_pool_config,
    payload_slot_offset,
    payload_slot_ptr,
    payload_slot_view,
    payload_view,
    poll_attach!,
    poll_attach,
    poll_control!,
    poll_descriptor!,
    poll_driver_control!,
    poll_driver_responses!,
    poll_discovery_response!,
    poll_qos!,
    poll_timers!,
    producer_config_from_attach,
    producer_do_work!,
    offer_frame!,
    commit_slot!,
    read_superblock,
    read_tensor_slot_header,
    refresh_activity_timestamps!,
    republish_descriptor!,
    try_claim_slot!,
    reset!,
    reset_mappings!,
    sbe_message_length,
    select_pool,
    send_attach!,
    send_attach_request!,
    request_attach_consumer,
    request_attach_producer,
    send_detach!,
    send_discovery_request!,
    send_keepalive!,
    seqlock_begin_write!,
    seqlock_commit_write!,
    seqlock_is_committed,
    seqlock_sequence,
    seqlock_read_begin,
    seqlock_read_end,
    supervisor_do_work!,
    with_claimed_buffer!,
    with_claimed_slot!,
    try_read_frame!,
    validate_stride,
    validate_discovery_endpoints,
    validate_bridge_config,
    validate_superblock_fields,
    validate_uri,
    wrap_superblock!,
    wrap_tensor_header!,
    write_superblock!,
    write_tensor_slot_header!

end
