module AeronTensorPool

using Aeron
using Agent
using Clocks
using Mmap
using SBE
using UnsafeArrays

include("gen/ShmTensorpoolControl.jl")
using .ShmTensorpoolControl
include("gen/ShmTensorpoolDriver.jl")
using .ShmTensorpoolDriver
include("gen/ShmTensorpoolBridge.jl")
using .ShmTensorpoolBridge

include("core/constants.jl")
include("core/errors.jl")
include("shm/shm_io.jl")
include("aeron/aeron_utils.jl")
include("aeron/counters.jl")
include("timers/polled_timer.jl")
include("driver/config.jl")
include("driver/state.jl")
include("driver/handlers.jl")
include("driver/logic.jl")
include("client/driver_proxies.jl")
include("client/driver_poller.jl")
include("client/driver_client.jl")
include("agents/producer/state.jl")
include("agents/producer/handlers.jl")
include("agents/producer/logic.jl")
include("agents/consumer/state.jl")
include("agents/consumer/handlers.jl")
include("agents/consumer/logic.jl")
include("agents/supervisor/state.jl")
include("agents/supervisor/handlers.jl")
include("agents/supervisor/logic.jl")
include("agents/bridge/state.jl")
include("agents/bridge/logic.jl")
include("agents/decimator/state.jl")
include("agents/decimator/logic.jl")
include("agents/producer_agent.jl")
include("agents/consumer_agent.jl")
include("agents/supervisor_agent.jl")
include("agents/driver_agent.jl")
include("agents/bridge_agent.jl")
include("config/config_loader.jl")

export Dtype,
    MajorOrder,
    RegionType,
    DriverHugepagesPolicy,
    DriverResponseCode,
    DriverRole,
    DriverPublishMode,
    DriverLeaseRevokeReason,
    DriverShutdownReason,
    MAGIC_TPOLSHM1,
    SUPERBLOCK_SIZE,
    HEADER_SLOT_BYTES,
    MAX_DIMS,
    PayloadPoolConfig,
    DriverPoolConfig,
    DriverProfileConfig,
    DriverStreamConfig,
    DriverPolicies,
    DriverShmConfig,
    DriverEndpoints,
    DriverConfig,
    ProducerConfig,
    ProducerState,
    ProducerAgent,
    ProducerInfo,
    ConsumerConfig,
    ConsumerConfigMsg,
    ConsumerState,
    ConsumerAgent,
    ConsumerInfo,
    SupervisorConfig,
    SupervisorState,
    SupervisorAgent,
    DriverAgent,
    DriverState,
    BridgeAgent,
    BridgeConfig,
    BridgeMapping,
    BridgeSourceInfo,
    BridgeAssembledFrame,
    BridgeSenderState,
    BridgeReceiverState,
    DecimatorConfig,
    DecimatorState,
    ConsumerHello,
    FrameDescriptor,
    FrameProgress,
    MessageHeader,
    DriverMessageHeader,
    QosProducer,
    ShmRegionSuperblock,
    ShmUri,
    SuperblockFields,
    SystemConfig,
    BridgeSystemConfig,
    TensorSlotHeader256,
    TensorSlotHeader,
    PayloadSlice,
    ConsumerFrameView,
    Mode,
    QosConsumer,
    ShmAttachRequest,
    ShmAttachResponse,
    ShmDetachRequest,
    ShmDetachResponse,
    ShmLeaseKeepalive,
    ShmDriverShutdown,
    ShmLeaseRevoked,
    seqlock_begin_write!,
    seqlock_commit_write!,
    seqlock_read_begin,
    seqlock_read_end,
    seqlock_is_write_in_progress,
    seqlock_frame_id,
    header_commit_ptr,
    header_commit_ptr_from_offset,
    TensorPoolError,
    ShmUriError,
    ShmValidationError,
    AeronInitError,
    Counters,
    ProducerCounters,
    ConsumerCounters,
    SupervisorCounters,
    DriverCounters,
    BridgeCounters,
    add_counter,
    make_counter_type_id,
    PolledTimer,
    TimerSet,
    due!,
    reset!,
    poll_timers!,
    init_consumer,
    init_producer_from_attach,
    producer_config_from_attach,
    init_consumer_from_attach,
    init_supervisor,
    init_bridge_sender,
    init_bridge_receiver,
    init_decimator,
    bridge_forward_announce!,
    bridge_send_frame!,
    bridge_sender_do_work!,
    bridge_receiver_do_work!,
    bridge_rematerialize!,
    map_from_announce!,
    map_from_attach_response!,
    emit_consumer_config!,
    emit_announce!,
    emit_consumer_hello!,
    emit_progress_complete!,
    emit_qos!,
    header_slot_offset,
    payload_slot_offset,
    payload_slot_view,
    payload_slot_ptr,
    payload_view,
    handle_consumer_hello!,
    handle_shm_pool_announce!,
    init_producer,
    init_consumer,
    init_driver,
    mmap_shm,
    parse_shm_uri,
    publish_frame!,
    read_superblock,
    read_tensor_slot_header,
    refresh_activity_timestamps!,
    reset_mappings!,
    select_pool,
    try_read_frame!,
    apply_consumer_config!,
    validate_uri,
    validate_stride,
    validate_superblock_fields,
    canonical_epoch_dir,
    canonical_header_uri,
    canonical_pool_uri,
    canonical_shm_paths,
    wrap_superblock!,
    wrap_tensor_header!,
    make_control_assembler,
    make_descriptor_assembler,
    poll_control!,
    poll_descriptor!,
    poll_qos!,
    supervisor_do_work!,
    producer_do_work!,
    consumer_do_work!,
    driver_do_work!,
    poll_driver_control!,
    make_qos_assembler,
    next_header_index,
    payload_pool_config,
    publish_frame_from_slot!,
    reserve_slot!,
    publish_reservation!,
    SlotReservation,
    InflightQueue,
    inflight_empty,
    inflight_full,
    inflight_push!,
    inflight_peek,
    inflight_pop!,
    bridge_frame!,
    handle_decimated_frame!,
    republish_descriptor!,
    write_superblock!,
    write_tensor_slot_header!,
    load_producer_config,
    load_driver_config,
    load_consumer_config,
    load_supervisor_config,
    load_system_config,
    load_bridge_config,
    try_claim_sbe!,
    sbe_message_length,
    AttachRequestProxy,
    KeepaliveProxy,
    DetachRequestProxy,
    send_attach!,
    send_keepalive!,
    send_detach!,
    DriverPoolInfo,
    AttachResponseInfo,
    DetachResponseInfo,
    LeaseRevokedInfo,
    DriverShutdownInfo,
    DriverResponsePoller,
    poll_driver_responses!,
    poll_attach!,
    DriverClientState,
    init_driver_client,
    send_attach_request!,
    driver_client_do_work!,
    await_attach!

end
